### ISSUE TITLE
Warnmeldung im Log

### ISSUE THREAD

**Issue by Siggi0904** [Pittini/iobroker-heatingcontrol-vis#11]
Hallo Pittini,

die Heizsaison ging heute los.
Das Addon machte auch pünklich los und alles funktioniert super.

Aber zwei Punkte.

1. Warnmeldung im Log
Es erscheint nun stündlich 

heatingcontrol.0 | 2020-10-01 17:09:03.366 | warn | (9288) override time not valid: 00:00
heatingcontrol.0 | 2020-10-01 17:09:03.324 | info | (9288) change temperature override for room Bad

Wo kommt denn das her? Was kann ich dagegen machen?

2. Umschaltung der Profile
Ich hatte gestern abend noch vom Profil Mo-So auf Mo-Fr + Sa, So umgestellt.
Die Objekte des alten Profils bleiben aber unter Objekte erhalten.
Ist das so gewollt? Wäre doch besser, wenn die gelöscht werden würden, oder zumindest eine Nachfrage kommen würde.

**Comment by Pittini** [comment]
Weder hat mein Vis was mit Logmeldungen zu tun, noch könnte es irgendwas löschen, beides sind Sachen welche Du mit dem HeatingControl Entwickler klären solltest. > https://github.com/rg-engineering/ioBroker.heatingcontrol
