### ISSUE TITLE
Vis nicht importierbar

### ISSUE THREAD

**Issue by Sum0mike** [Pittini/iobroker-heatingcontrol-vis#13]
Hallo Pittini,

ich habe versucht deine VIS (V3.0.1) nach der Anleitung zu importieren. Leider bekomme ich folgende Fehlermeldung:
![FM_Vis](https://user-images.githubusercontent.com/76756889/103321400-cbef9700-4a39-11eb-994b-65626b4f5874.JPG)

Andere VIS-Projekte lassen sich ohne Fehlermeldung importieren, daher gehe ich von keinen in der VIS- oder iobroker-Konfig aus. Kannst du bei dieser Fehlermeldung weiterhelfen?

Viele Grüße
Sumo

**Comment by Pittini** [comment]
Fehlerhafter Download. Wie groß is die Datei die Du vorliegen hast? Sollte 2,42MB haben.

**Comment by bestguy62** [comment]
Selbe Fehlermeldung. Mein Download von heute hat 89 kB.

**Comment by Sum0mike** [comment]
Klassicher Anwenderfehler bei mir. Die Zip-Datei muss 2,43MB haben. Ich vermute du hast (wie ich) nur einen Link o.ä. heruntergeladen. 
@bestguy62 mach den Download nochmal über den Button (siehe Bild)
![FM_Vis2](https://user-images.githubusercontent.com/76756889/103365505-832ef100-4ac0-11eb-82e0-8842dc97c2f5.JPG)

**Comment by bestguy62** [comment]
Hat geklappt, danke. Ich habe das gesamte Projekt als zip heruntergeladen, aus der Gesamt-Zip die V3.0.1-Vis-HeatingControl.zip extrahiert und diese importiert.

**Comment by Frankyno1** [comment]
Hallo 
vielleicht kann mir jemand helfen , ich habe auch ein kleines Import problem   und zwar  nach dem ich als projektname "HeatingControl" angegeben habe und auf das zip File verweise (V3.3.0-Vis-HeatingControl.zip) und dann den button <IMPORT PROJEKT> klicke  bekomme ich eine kurze rote meldung "VERBINDUNGSFEHLER" 
![verbindungsfehler](https://user-images.githubusercontent.com/79717817/193392382-27cbc2fc-3dfc-4cf0-b279-781cb92203f7.JPG)
Danke und ein schönes weeeekend allen

**Comment by Pittini** [comment]
> Hallo vielleicht kann mir jemand helfen , ich habe auch ein kleines Import problem und zwar nach dem ich als projektname "HeatingControl" angegeben habe und auf das zip File verweise (V3.3.0-Vis-HeatingControl.zip) und dann den button klicke bekomme ich eine kurze rote meldung "VERBINDUNGSFEHLER" ![verbindungsfehler](https://user-images.githubusercontent.com/79717817/193392382-27cbc2fc-3dfc-4cf0-b279-781cb92203f7.JPG) Danke und ein schönes weeeekend allen

Siehe das angepinnte Issue. https://github.com/Pittini/iobroker-heatingcontrol-vis/issues/21

**Comment by Nusseis635** [comment]
Hi, 
habe auch das Problem mit dem Verbindungsfehler! Habe die oberen Schritte alle befolgt. Die Dateigrößen stimmen. Egal welche Version, es kommt immer "Verbindungsfehler"

Danke...

**Comment by Pittini** [comment]
> Hi, habe auch das Problem mit dem Verbindungsfehler! Habe die oberen Schritte alle befolgt. Die Dateigrößen stimmen. Egal welche Version, es kommt immer "Verbindungsfehler"
> 
> Danke...

Siehe das angepinnte Issue. https://github.com/Pittini/iobroker-heatingcontrol-vis/issues/21
