### ISSUE TITLE
 Popup for times / weeks menu does not work in VIS

### ISSUE THREAD

**Issue by TJJochen** [Pittini/iobroker-heatingcontrol-vis#15]
If you want to change the settings for the currently marked period in the times / weeks menu in the VIS, the selection popup does not appear. Only for the unmarked periods.

![Popup](https://user-images.githubusercontent.com/35068587/105165571-c952ff80-5b16-11eb-8d4f-7de9e4d8d514.PNG)
![Popup1](https://user-images.githubusercontent.com/35068587/105165577-cb1cc300-5b16-11eb-8518-e2606b16f383.PNG)

**Comment by Pittini** [comment]
This is a known and fixed bug. Please use the neweset version 3.1.2. If the problem still exists, report.

**Comment by TJJochen** [comment]
Hello Pittini ...

Thx for the quick answer and solution. It works with version 3.1.2. perfect.
Post can be closed and marked as solved. :-)

Greetz Jochen
