### ISSUE TITLE
Markiertes Profil falsch

### ISSUE THREAD

**Issue by CaptainBalou** [Pittini/iobroker-heatingcontrol-vis#16]
Das als aktiv markierte Profil scheint falsch zu sein. Es ist aktuell 12:56 Uhr und auf der VIS Seite steht:

<img width="376" alt="grafik" src="https://user-images.githubusercontent.com/17015872/105629523-c83a0f00-5e43-11eb-9902-e1b4f7ba382f.png">

Laut Raumlog wurde jedoch um 12:01 Uhr die korrekte Temperatur gesetzt:

<img width="319" alt="grafik" src="https://user-images.githubusercontent.com/17015872/105629541-e56edd80-5e43-11eb-8a9f-46e9b1615fd6.png">

**Comment by CaptainBalou** [comment]
Im Einsatz befindet sich die Version 3.1.2

<img width="341" alt="grafik" src="https://user-images.githubusercontent.com/17015872/105629568-09caba00-5e44-11eb-9bb2-d00e5eb2da41.png">

**Comment by Pittini** [comment]
> Im Einsatz befindet sich die Version 3.1.2

Und welche Version vom HeatingControl Adapter?

**Comment by CaptainBalou** [comment]
Version 2.0.2 vom HeatingControlAdapter. Mit der 2.0.1 davor war es aber auch.

**Comment by Pittini** [comment]
Wenn das bei Dir falsch ist, dann gib bitte mal durch was in den Dps:

heatingcontrol.0.Rooms.Wohnzimmer.ActiveTimeSlot
heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriod
heatingcontrol.0.Rooms.Wohnzimmer.CurrentTimePeriodFull
und
heatingcontrol.0.vis.RoomValues.CurrentTimePeriod

drinsteht. Es sollte im Vis der fehlerhafte Raum angezeigt sein während Du das machst.

**Comment by CaptainBalou** [comment]
Hallo Pittini,

es ist aktuell 20:49 Uhr CET. Im VIS GUI steht:

<img width="375" alt="grafik" src="https://user-images.githubusercontent.com/17015872/105641679-b1b4a780-5e85-11eb-9b8a-8b88934e251b.png">

Die Variablen sind wie folgt:

<img width="1298" alt="grafik" src="https://user-images.githubusercontent.com/17015872/105641719-e9235400-5e85-11eb-8464-61690715978c.png">

<img width="1254" alt="grafik" src="https://user-images.githubusercontent.com/17015872/105641764-1f60d380-5e86-11eb-9b08-f4b902912ed7.png">

Ich hoffe das passt so. Ansonsten bitte nochmal einen Hinweis was du brauchst. Danke.

**Comment by Pittini** [comment]
> Ich hoffe das passt so. Ansonsten bitte nochmal einen Hinweis was du brauchst. Danke.

Danke, ich seh schon das Problem, liegt nicht direkt am Vis, muß ich an Rene weitergeben. Letztendlich würde es sofort passen wenn Du 5 Perioden verwenden würdest, ansonsten mußt warten bis Rene das im Adapter gefixt hat. @rg-engineering
