### ISSUE TITLE
lbar immer auf nach Aktualisierung

### ISSUE THREAD

**Issue by m1chel87** [Pittini/iobroker-heatingcontrol-vis#20]
Jedes mal wenn die Vis Seite neu geladen wird popt an der linken Seite die Menüleiste "lbar" auf.
Kann man das ändern, dass die nur noch durch klicken auf geht?

**Comment by Pittini** [comment]
Was hast Du in den mdui Einstellungen, bei Standard, ganz unten (lnav fixiert ab) drin stehen? Normalerweise steht da nix drin, wenn doch liegts daran, kannst ja mal 5000 reinschreiben, dann würde die lnav erst ab Auflösungen mit 5k Breite erscheinen.
Wenns was anderes ist, bitte nicht bei mir, sondern beim mdui Dev melden, ich nutz das ja nur.
https://github.com/Uhula/ioBroker-Material-Design-Style

**Comment by m1chel87** [comment]
@Pittini die 5000 hat gewirkt! Vielen Dank dafür.
Jetzt habe ich aber trotzdem noch eine Frage. In meinem Log bekomme ich vom Web Adapter immer eine Warnung 
-->"State "0_userdata.0.mdui.vis.lnav_fixed_width" has no existing object, this might lead to an error in future versions"<--
Anscheinend muss da was angelegt sein. Hab ich bei der Installation einen Fehler gemacht?

**Comment by Pittini** [comment]
> In meinem Log bekomme ich vom Web Adapter immer eine Warnung -->"State "0_userdata.0.mdui.vis.lnav_fixed_width" has no existing object, this might lead to an error in future versions"<-- Anscheinend muss da was angelegt sein. Hab ich bei der Installation einen Fehler gemacht?

Das is nich meine Baustelle, sorry. Wie oben schon erwähnt, wenn mdui nen Fehler verursucht an den mdui Dev wenden. Entweder hier als Issue oder im Forum mal nachfragen: https://forum.iobroker.net/topic/30363/projekt-mdcss-v2-material-design-css-version-2/715

**Comment by m1chel87** [comment]
ok! Ich werde mich dorthin wenden. Vielen Dank!!!
