### ISSUE TITLE
Import Problem (v3.3.0)

### ISSUE THREAD

**Issue by Karkas66** [Pittini/iobroker-heatingcontrol-vis#21]
Hi,

wenn ich versuche die (korrekt runtergeladene und im explorer sauber entpackbare) ZIP Datei in VIS zu importieren sagt er mir immer "Verbindungsfehler" und bricht ab. Getestet mit 2 verschiedenen Browsern auf jeweils 2 verschiedenen Geräten. Netzwerkproblem kann ich auch ausschließen.

Gibt es irgendwo größenbeschränkungen oder sowas? 

Vielleicht kann ich die Dateien per WinSCP auf den IoBroker senden, damit sie gezogen werden. Finde nur das richtige verzeichnis nicht

**Comment by Pittini** [comment]
Nö das gibts keine Größenbeschränkungen. Und ich sags mal so, das Ding is bei sovielen Leuten im Einsatz, ohne Probleme beim Import, dass ich davon ausgehe dass bei Dir was schiefläuft. Was genau kann ich Dir auch nicht sagen. Kannst ja mal im Forum im HC Thread fragen ob wer ne Idee hat.

**Comment by Karkas66** [comment]
Danke, hab hier andere gefunden, die das Problem auch haben:

https://github.com/ioBroker/ioBroker.vis/issues/510

**Comment by Karkas66** [comment]
Problem ist gefixt, ich musste folgende Einstellung in der Webserver Instanz setzen:

![image](https://user-images.githubusercontent.com/25013261/192284035-9e4a5cf9-994a-44ff-9084-8540ffb532f9.png)

**Comment by Pittini** [comment]
Ok, danke Dir. Liegt ja wie vermutet völlig außerhalb meiner Einflußmöglichkeiten und deswegen mach ich hier mal dicht.
