### ISSUE TITLE
Ext. Temperatures seems not to work prop.

### ISSUE THREAD

**Issue by DJ3vil** [Pittini/iobroker-heatingcontrol-vis#22]
![image](https://user-images.githubusercontent.com/22053738/194144442-f08675f0-f8ff-452a-9be5-8c744bc4216c.png)

Hey the external Temp Sensor seems sometimes not to work. 
I alrdy saw it here an there, but mostly there stands n/a.

Ive got the SNZB 02 from Sonos, they provide the Temp in XX,XX format.

Cheers

**Comment by Pittini** [comment]
Vis only shows what the HeatingControl Adapter provides, so please go there.
