### ISSUE TITLE
Datenpunkt  heatingcontrol.0.Profiles.1.Wohnzimmer.Mo-Fr.Periods.1 Verständnisfrage

### ISSUE THREAD

**Issue by git828** [Pittini/iobroker-heatingcontrol-vis#23]
Hallo 
Ich setzte im view cardHzngMoFrSaSo eine Zeit oder eine Temperatur für den Raum Wohnzimmer.
![image](https://user-images.githubusercontent.com/58549168/194902987-e72d1391-7383-49a7-87f3-bf98f567c6f9.png)
Dies erzeugt im Datenpunkt  heatingcontrol.0.**vis**.ProfileTypes.Mo-Fr.Periods.4 auch den richtigen Eintrag.
![image](https://user-images.githubusercontent.com/58549168/194903345-ce90f313-884e-4390-a48f-9dd7bdd00abf.png)

Nur der Datenpunkt heatingcontrol.0.Profiles.1.Wohnzimmer.Mo-Fr.Periods.4 zeigt nicht den richtigen Wert.
![image](https://user-images.githubusercontent.com/58549168/194903575-0c37d315-29be-44c0-8a5d-272545ac7d04.png)

Was mach Ich falsch? Hab so ziemlich alles ausprobiert ohne Erfolg.
Sollte hier irgendwo ein Script laufen das diesen Wert von vis auf Wohnzimmer  kopiert ?

Danke.

**Comment by Pittini** [comment]
> Dies erzeugt im Datenpunkt heatingcontrol.0.**vis**.ProfileTypes.Mo-Fr.Periods.4 auch den richtigen Eintrag.

Na das ist ja fein, denn damit bin ich raus. Wenn das nicht ins Profile kopiert wird oder Du was falsch eingestellt hast...bitte am besten im Forum beim HC Thread melden.

**Comment by git828** [comment]
Danke ;)
