### ISSUE TITLE
Fenster Raumstatus lässt sich nicht vergrößern

### ISSUE THREAD

**Issue by McWoolf** [Pittini/iobroker-heatingcontrol-vis#24]
Hallo.

Als erstes mal super Arbeit, danke dafür.
Ich  bin nur zu dämlich anscheinend das View für den Raumstatus zu vergrößern, Hintergrund ich will keinen scroll-Balken haben, da sich die Vis immer so schnell aktualisiert, dass ich die unteren Stati nicht sehen kann, bzw. nur kurz. Somit würde ich gerne das Fenster einfach größer machen, aber wenn ich in contHzng das Felster größer ziehe, geht das immer in den Ausgangszustand zurück.
Kannst du mir hier bitte helfen?

Danke
![image](https://user-images.githubusercontent.com/73942255/198948284-d8bae6fa-444d-4422-ba27-e71ad6bbf376.png)

**Comment by Pittini** [comment]
Ja, is klar, das wird überschrieben. Die Höhen und Breiten der cards folgen einem festen Schema und werden in den Eigenschaften bei der CSS-Klasse mit den Einträgen "mdui-cols-6 mdui-rows-4" festgelegt. Da kannste das auch auf die nächste Größe hochsetzen.

**Comment by McWoolf** [comment]
Hmm dann war ich schon auf dem richtigen Weg, aber ich weiß nicht wo ich das hochstellen kann.

Von meinem iPad gesendet

> Am 31.10.2022 um 10:43 schrieb Pittini ***@***.***>:
> 
> mdui-cols

**Comment by Pittini** [comment]
> Hmm dann war ich schon auf dem richtigen Weg, aber ich weiß nicht wo ich das hochstellen kann.

Hab ich Dir doch oben schon geschrieben. In der contHzng, die entsprechende card anklicken, dann im Eigenschaftenfenster bei css Klasse das mdui-rows-4 z.B. auf mdui-rows-5 hochsetzen.

**Comment by McWoolf** [comment]
Ach Gott, danke dir.
Manchmal sieht man den Wald vor lauter Bäumen nicht.

Von meinem iPad gesendet
