### ISSUE TITLE
Raumtemperaturen und Zeiten Speichern

### ISSUE THREAD

**Issue by Fichte79** [Pittini/iobroker-heatingcontrol-vis#26]
Hallo zusammen

Kann es sein das deine VIS nur Daten liest?
Ich kann die werte wie Zeiten und Temperaturen nichgt Speichern.

LG Fichte

**Comment by Pittini** [comment]
Das Vis is bei zig Leuten im Einsatz ohne Probs, also nein, kann nicht sein. Wenn was nicht klappt, hat man sich i.d.R. nicht an die Anleitung gehalten oder der Adapter selbst ist nicht richtig konfiguriert.
