### ISSUE TITLE
Die View "pageHzng" funktioniert nicht mehr

### ISSUE THREAD

**Issue by copperfield74** [Pittini/iobroker-heatingcontrol-vis#30]
Hallo, heute hat plötzlich die Übersicht pageHzng den Geist aufgegeben.
Wenn ich versuche die Seite aufzurufen, dann wird das Sichfenster grau und nichts passiert.
Habe versucht die view zu löschen und eine neue frische zu importieren, leider auch ohne Erfolg.
Wenn ich versuche die View in der neuen Installation zu öffnen, dann geht es, aber wenn ich sie in meine alte Installation importiere wieder der gleiche Fehler.
![grafik](https://github.com/user-attachments/assets/98ccfbda-688e-4492-adfc-c896eb2a2597)

**Comment by Pittini** [comment]
Naja, dann stimmt offensichtlich mit Deiner Installation iwas nicht, da kann ich Dir auch nicht helfen, is ja kein Fehler der View selber.
