### ISSUE TITLE
coninuously send a warning to log

### ISSUE THREAD

**Issue by EdgarM73** [Pittini/iobroker-heatingcontrol-vis#6]
Hi Pittini,

thanks for this great plugin, it works really good.

Only one thing wonders me, if I did configure something wrong or there is a bug.

In My logfile all the time this waring happens, but i do not know why.

I did set the override to inactive, so it shouldnt even happen.

 
heatingcontrol.0 | 2020-06-10 12:08:38.859 | warn | (24141) override time not valid: 00:00
-- | -- | -- | --

regards

**Comment by Pittini** [comment]
Not an Vis Issue, please report to the heatincontrol adapter developer.
