### ISSUE TITLE
Habe problem mit instalation

### ISSUE THREAD

**Issue by Vraanaa** [Pittini/iobroker-heatingcontrol-vis#8]
Hallo,

Ich habe di letzte Version heruntergeladen - hat alles auch beschreibung gemacht und Fehler gekommt:
![image](https://user-images.githubusercontent.com/70016007/92334085-0304fb80-f08b-11ea-8e45-58abcb2d8d69.png)

![image](https://user-images.githubusercontent.com/70016007/92334093-11ebae00-f08b-11ea-9b03-d2485ef6fb25.png)

![image](https://user-images.githubusercontent.com/70016007/92334097-2039ca00-f08b-11ea-859b-2e74be2104b3.png)

Was habe ich falsch gemacht - danke vorab.

**Comment by Pittini** [comment]
> Was habe ich falsch gemacht - danke vorab.

Keine Ahnung, kannst Du denn andere Projekte importieren? Sieht mir nach nem Problem mit Vis aus.

**Comment by Vraanaa** [comment]
Hallo Pittini, danke für schnelle Antwort. Ich habe problem gelöst. Etwas mit herunterlaen war Problem, so das mein erst heruntengeladene Projekt war nur 105kB, dann Heute ich finde da ist ein mit 2.484kB. Es geht alles prima mit diese 2.484kB file:
![image](https://user-images.githubusercontent.com/70016007/92366475-7e02fc00-f0f5-11ea-8706-9cd2e91a5d74.png)

Diese Richtige File habe ich von hier Heruntergeladen:
![image](https://user-images.githubusercontent.com/70016007/92366698-c9b5a580-f0f5-11ea-9d72-a034d638cc85.png)
