### ISSUE TITLE
Gekippte Fenster anzeigen

### ISSUE THREAD

**Issue by Denkra** [Pittini/iobroker-heatingcontrol-vis#9]
Hi.

In deinem Script konnte man sich ja auch gekippte Fenster anzeigen lassen. Funktioniert das in der Vis für den Adapter auch?

**Comment by Pittini** [comment]
Soweit ich weis, hat Rene das 1:1 übernommen gehabt, sollte also klappen.
Wenns auch n bisserl mehr sein darf, inkl Türen, kannste Dir auch das aktuelle Skript anschauen, das kann noch mehr: https://github.com/Pittini/iobroker-Fensterauswertung

**Comment by Denkra** [comment]
Okay weil er macht es nicht wie in dem Script was ich auch am laufen habe. Man hat auch keine möglichkeiten zu sagen wie der State heißen muss damit das Fenster als gekippt angezeigt wird. Es sind zwar welche in dem Script hinterlegt aber nicht der, der bei mir angezeigt wird wenn Fenster gekippt.  Wenn ich das Script verwende funktioniert es auch, nur die formatierung ist nicht richtig in der Vis beim Adapter.

**Comment by Pittini** [comment]
Ja, die Fensteroffenthematik beim Adapter ist die, dass hier auf die Datenpunkte zugegriffen wird, die im Adapteradmin eingetragen sind. Das war als zusätzlicher BonBon gedacht um nen schnellen Überblick zu haben. Grundsätzlich ist dafür aber seit Integration in den Adapter Rene zuständig und Ansprechpartner.
Wenns mit allem Schnickschnack sein soll, dann eben das oben verlinkte Skript, das sollte alle Varianten abdecken, dafür gibts ja auch ein eigenes Vis Beispiel. Ansonsten bitte ganz konkret das Problem schildern, sonst kann ich ned wirklich helfen.

**Comment by Denkra** [comment]
Also ich habe deine Vis in benutzung. Die Fenster offen erkennung über den Adapter funktioniert auch. Wenn zu zusätzlich das Script benutze von dir das mir auch gekippte Fenster anzeigt, dann zeigt er es in der Vis vom Adapter falsch an. Muss scrollen weil er oben noch die Anzahl anzeigt und da die Schrift zu groß dafür ist wahrscheinlich, zieht er es in 4 Zeilen. Die Stunden zum Beispiel stehen hinter "geschlossen" etc. Dazu kommt noch, das der Zeitstempel nicht aktualisiert wird.

Adapter
![Screenshot_675](https://user-images.githubusercontent.com/47492483/92712059-72b00a80-f359-11ea-8b8e-3e6d97779cda.jpg)

Script
![Screenshot_676](https://user-images.githubusercontent.com/47492483/92712092-7e9bcc80-f359-11ea-8f02-131bb659c99b.jpg)

**Comment by Denkra** [comment]
Sobald ich ein Fenster zu mache, hängt sich das Script auch auf und sagt mir einen Error in Zeile 1037:38 und 1339:29

**Comment by Pittini** [comment]
Welche Skriptversion? Welcher Error? Startlog?
 Und klar passt die größere Anzeige vom Skript nicht in den kleinen Bereich der Vis Vorlage vom HeatingControl Vis. Machs halt breiter dann is auch das 4 Zeilen Problem weg.

**Comment by Denkra** [comment]
Scriptversion ist die aktuelle die im Git ist. Den Rest kann ich heute Abend schreiben wenn ich Feierabend habe.

**Comment by Denkra** [comment]
11:41:11.531 | error | javascript.0 (1912) at CheckWindow (script.js.common.Fensterauswertung:1037:38)
-- | -- | --
11:41:11.532 | error | javascript.0 (1912) at Object.<anonymous> (script.js.common.Fensterauswertung:1339:29)

Sind die Errors die er im JS anzeigt.

Im Log zeigt er das hier an...
![Screenshot_677](https://user-images.githubusercontent.com/47492483/92810915-437fb480-f3be-11ea-8b45-8d45e657f126.jpg)

**Comment by Denkra** [comment]
Ah glaube Fehler gefunden. Eventlog musste noch deaktiviert werden. Aber was noch ist, der Timestamp wird nicht aktualisiert.

**Comment by Pittini** [comment]
> Aber was noch ist, der Timestamp wird nicht aktualisiert.

Screen? Startlog?
